alter table CLINIC_VETERINARIAN add constraint FK_CLINIC_VETERINARIAN_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_CLINIC_VETERINARIAN_ON_USER on CLINIC_VETERINARIAN (USER_ID);
